### ISSUE TITLE
random segfault in s3 crt cpp client when uploading

### ISSUE THREAD

**Issue by g76r** [awslabs/aws-crt-cpp#382]
I encounter some random segfault within s3 crt cpp client when uploading files (in parallel, to the same bucket), this seems related to name resolving but I'm not sure.
about 10% of my large batches encounter that.
not (until now) at the begining of the process but after a lot of files have been uploaded (maybe 20 to 100)

what could help apart the stacktrace shown below ?

thanks in advance.

```
(gdb) where
#0  0x00007f2a8984c6bc in aws_hash_string (item=0x6865765f6c766600)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/hash_table.c:965
#1  0x00007f2a8984c05f in s_hash_for (key=0x6865765f6c766600, state=0x55a8c5b833a0)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/hash_table.c:48
#2  aws_hash_table_find (map=map@entry=0x55a8c5b83118, key=0x6865765f6c766600, p_elem=p_elem@entry=0x7f2a85622388)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/hash_table.c:402
#3  0x00007f2a897932c2 in default_get_host_address_count (host_resolver=<optimized out>, host_name=<optimized out>, flags=1)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-io/source/host_resolver.c:1516
#4  0x00007f2a89b89be0 in aws_s3_client_update_meta_requests_threaded (client=client@entry=0x55a8c5c9af20)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-s3/source/s3_client.c:1217
#5  0x00007f2a89b8a584 in s_s3_client_process_work_default (client=0x55a8c5c9af20)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-s3/source/s3_client.c:1073
#6  0x00007f2a89850932 in s_run_all (scheduler=scheduler@entry=0x55a8c5b7ea30, current_time=1990735528099,
    status=status@entry=AWS_TASK_STATUS_RUN_READY)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:249
#7  0x00007f2a89850e47 in aws_task_scheduler_run_all (scheduler=scheduler@entry=0x55a8c5b7ea30, current_time=<optimized out>)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/task_scheduler.c:188
#8  0x00007f2a89797a74 in s_main_loop (args=<optimized out>)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-io/source/linux/epoll_event_loop.c:635
#9  0x00007f2a8984ff57 in thread_fn (arg=0x55a8c5b7aa20)
    at /builds/anonimized/aws-sdk-cpp/crt/aws-crt-cpp/crt/aws-c-common/source/posix/thread.c:137
#10 0x00007f2a889deea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#11 0x00007f2a88ceddef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by jmklix** [comment]
Make sure that you are not shutting down the s3 handle while you are still trying to upload files

Can you please provide more details and a minimal reproducible code sample?

**Comment by g76r** [comment]
well...
I'm almost sure I didn't shut down the handles because I used only one thread, but anyway I got rid of the crt driver for a long time now, since the segfault in production were not bearable for 8 months.
so I'm not sure I can be of any help anymore.
sorry.

**Comment by jmklix** [comment]
Sorry, that we weren't able to fix this for you. Please let us know if you run into this again
